---
title: "Hemp Phytobiomes repo"
output: html_notebook
---
# Packages

# Datasets

## Fungicide

## Corn Earworm Exp
```{r}
worm.dat.loc=here::here("corn earworm")

# Data for CHOICE TRIAL
choice <- read.csv(paste0(worm.dat.loc, "/ChoiceTrialData_CornEarwormOR.csv"), header = TRUE, sep = ",")
str(choice)
head(choice)


# Upload the other data set that contains overall food choice 
food <- read.csv(paste0(worm.dat.loc, "/ChoiceTrialData_FoodMass.csv"), header = TRUE, sep = ",")
str(food)


# Load dataset for cox analysis # 
corncox <- read.csv(paste0(worm.dat.loc, "/cox_cornearnworm.csv"), header = TRUE, sep = ",")
# note - status column indicates if dead, 1 = dead, 0 = pupated

# Data for SURVIVAL TRIAL 
levels <- read.csv(paste0(worm.dat.loc, "/LevelsTrialData_CornEarwormOR.csv"), header = TRUE, sep = ",")
str(levels)
```

Data Analysis

# Corn Earworm Experiment

## Survival
### Perform Cox Proportional Hazards Regression 

```{r}

# Now, perform analysis
cox_survival<- coxph(formula = Surv(time, status) ~ diet.num, data = corncox)
cox_survival

# 
# coef exp(coef) se(coef)      z     p
# diet.num -0.1647    0.8482   0.1969 -0.836 0.403
# 
# Likelihood ratio test=0.7  on 1 df, p=0.402
# n= 45, number of events= 40 

res.cox.fit <- survfit(Surv(time, status) ~ diet, data = corncox)
ggsurvplot(res.cox.fit)
cox_z_survival<-cox.zph(cox_survival)
ggcoxzph(cox_z_survival)

ggsurvplot(res.cox.fit, 
            conf.int = T, conf.int.alpha= 0.2,
           palette= c("#E69F00","#7fcdbb", "#56B4E9"),
           legend.title =  "",
          legend.labs = c("High","Low", "Control"),
          risk.table = F,
  xlab("Days") +
  theme(legend.position = "top") )
```

